### ISSUE TITLE
Idk where does this problem come from can somone plz help me

### ISSUE THREAD

**Issue by Roywesley** [JRocketNFT/mirrorbot#2]
![Capture](https://user-images.githubusercontent.com/110842864/184560726-a6d55dfb-fdbb-4104-bcb9-46978fc61072.PNG)

**Comment by JRocketNFT** [comment]
Off quick visual inspection I cannot find in the original code. 
const existing = channel.messages.cache.get(data.id);

But I did not have time to do a deep dive yet.  Is this something you added?

**Comment by JRocketNFT** [comment]
Late to the party but you need to pull the inner mirror bot folder out and work from that folder and delete the outer one.  Your root folder should be mirrorbot that directly opens to the config, index, main, packagelock, package.  

If your root folder is mirrorbot that opens to another mirrorbot folder it will cause this error.
