### ISSUE TITLE
Module Not Found (FIXED)

### ISSUE THREAD

**Issue by nolancruiser** [JRocketNFT/mirrorbot#3]
Hey, thanks for your work. Ran the node main.js command and I get this: 
![modulenotfound](https://user-images.githubusercontent.com/112344215/187295605-21e22b64-9d90-4183-8a4c-c1bfd45a5c76.png)
What should I do?

**Comment by JRocketNFT** [comment]
Ensure you save the file to a location that is not your downloads folder.  For some reason I pulled this error while it was saved in my downloads folder.  

Ensure you are opening it up in VS Code using the Mirror Bot Folder Directory not from the mirrobot-main folder:

(YOUR DRIVE):\mirrorbot-main\mirrorbot-main\Mirror Bot

Example from my drive:   E:\mirrorbot-main\mirrorbot-main\Mirror Bot

This was not a known issue before the latest VS Code update.  

If you did it correctly you will not see the ReadMe in VS code.  I will fix this at a later time.
